# GitLab CI/CD 配置文件
# ETL 專案自動化部署

stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/
    - venv/

# 測試階段
test_connection:
  stage: test
  tags:
    - rocky
  script:
    - echo "開始進行資料庫連線測試..."
    - dnf install -y unixODBC unixODBC-devel
    - curl https://packages.microsoft.com/config/rhel/9/prod.repo > /etc/yum.repos.d/mssql-release.repo
    - ACCEPT_EULA=Y dnf install -y msodbcsql17
    - dnf install -y gcc-c++ python3-devel
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install pyodbc pandas
    - echo "檢查資料庫設定..."
    - grep -A 5 "source_db" db.json || echo "警告：找不到來源資料庫配置"
    - grep -A 5 "target_db" db.json || echo "警告：找不到目標資料庫配置"
    - python app.py
  artifacts:
    paths:
      - etl_log.log
    expire_in: 1 week
  only:
    - main
    - merge_requests

# 部署階段
deploy_etl:
  stage: deploy
  tags:
    - rocky
  script:
    - echo "開始進行 ETL 部署..."
    - chmod +x setup.sh
    - ./setup.sh install
  only:
    - main
  artifacts:
    paths:
      - setup_log.txt
      - etl_log.log
    expire_in: 1 week
  environment:
    name: production