SELECT [MANUFACTURING_OD] AS [工單號],
     [MATERIAL] AS [料號],
     [MATERIAL_DESC] AS [料號名稱],
     CAST(ISNULL([QTY], 0) AS DECIMAL(18,2)) AS [工單預計生產數量],
     CAST(CASE WHEN [PLANNED_S_DATE]<'17530101' THEN NULL ELSE [PLANNED_S_DATE] END AS DATETIME2) AS [工單預計開工日],
     CAST(CASE WHEN [PLANNED_C_DATE]<'17530101' THEN NULL ELSE [PLANNED_C_DATE] END AS DATETIME2) AS [工單預計完工日],
     CAST(ISNULL([QTY_DONE], 0) AS DECIMAL(18,2)) AS [工單實際完工數量],
     CAST(ISNULL([QTY_DONE], 0)-ISNULL([QTY], 0) AS DECIMAL(18,2)) AS [實際完工量-預計生產量],
     CAST(CASE WHEN [ACTUAL_S_DATE]<'17530101' THEN NULL ELSE [ACTUAL_S_DATE] END AS DATETIME2) AS [工單實際開工日],
     CAST(CASE WHEN [ACTUAL_C_DATE]<'17530101' THEN NULL ELSE [ACTUAL_C_DATE] END AS DATETIME2) AS [工單實際完工日],
     CASE WHEN [SHOP_ORD_STATUS]=1 THEN '已核' 
            WHEN [SHOP_ORD_STATUS]=2 THEN '生管已派' 
            WHEN [SHOP_ORD_STATUS]=3 THEN '加工中' 
            WHEN [SHOP_ORD_STATUS]=9 THEN '完成' 
            WHEN [SHOP_ORD_STATUS]=10 THEN 'SAP已核' 
            WHEN [SHOP_ORD_STATUS]=12 THEN '已結' 
            WHEN [SHOP_ORD_STATUS]=13 THEN '製造已派' 
            ELSE '' 
       END AS [MES工單狀態],
     CASE WHEN [SAP_ORD_STATUS]='P' THEN '已計畫' 
            WHEN [SAP_ORD_STATUS]='R' THEN '已核發' 
            WHEN [SAP_ORD_STATUS]='C' THEN '已取消' 
            WHEN [SAP_ORD_STATUS]='L' THEN '已結' 
            ELSE '' 
       END AS [SAP工單狀態],
     CAST(CASE WHEN [ACTUAL_C_DATE] IS NULL OR [PLANNED_C_DATE] IS NULL THEN 0 
                 ELSE DATEDIFF(dd,[PLANNED_C_DATE],[ACTUAL_C_DATE]) 
            END AS INT) AS [實際完工日-預計完工日],
     CASE WHEN [ACTUAL_C_DATE] IS NULL OR [PLANNED_C_DATE] IS NULL THEN '' 
            WHEN DATEDIFF(dd,[PLANNED_C_DATE],[ACTUAL_C_DATE])>0 THEN '延遲' 
            WHEN DATEDIFF(dd,[PLANNED_C_DATE],[ACTUAL_C_DATE])=0 THEN '如期' 
            WHEN DATEDIFF(dd,[PLANNED_C_DATE],[ACTUAL_C_DATE])<0 THEN '提前' 
            ELSE '' 
       END AS [工單狀態]
FROM [MANUFACTURING_NO]
WHERE [MATERIAL] IS NOT NULL